### ISSUE TITLE
Ability to handle cases where require is called with a non-literal parameter

### ISSUE THREAD

**Issue by fresheneesz** [browserify/detective#23]
Eg: `require("dep"+"endency");`

In the general case, it would be very nice if the value of statements passed into `require` could be statically determined (where possible), allowing detective to find dependencies described via function parameters, variables, or other non-literal sources.

It may be out of scope for this module, specifically, to have more arbitrary static analysis that can statically determine the value of statements, but it would certainly make this module more robust, and would be a pretty useful module in its own right. One case I'm thinking about is supporting something like this: https://npmjs.org/package/use

**Comment by goto-bus-stop** [comment]
`detective.find` returns an `expressions` property that you can use for this. Eg with static-eval to statically evaluate expression arguments:

```js
var r = require('detective').find(src)
var strings = r.strings.concat(
  r.expressions.map(function (expr) {
    var ast = require('acorn').parseExpressionAt(expr, 0)
    return require('static-eval')(ast, {})
  })
).filter(function (id) { return id !== undefined }) // filter things that are not statically eval-able
```
