### ISSUE TITLE
Skip commented-out requires

### ISSUE THREAD

**Issue by paulmillr** [browserify/detective#45]
Currently detective parses these as valid requires even though they are not.

``` javascript
require('b')
// require('c')
/*
  require('d')
*/
```

maybe with https://github.com/jonschlinkert/strip-comments

**Comment by zertosh** [comment]
I dig this idea. I took a quick look at strip-comments, and two things came to mind: (1) performance, but maybe it's not so bad; (2) strip-comments doesn't seem maintained anymore, not that it matters for the node-detective use case, but it removes comment-like things from strings (doesn't inspire confidence).

Any other ideas? I'd be awesome to be able to skip files if we can.

**Comment by paulmillr** [comment]
Not sure about other solutions. We can write our own solution that would do this on per-line iteration basis. Nothing fancy.

**Comment by jmm** [comment]
I must be misunderstanding something; how does Detective report those as requires when it uses the AST? Also, I don't get that when I try it with `detective@4.0.0`, which I presume was latest when this issue was created. I get only `["b"]` as the output.

**Comment by zertosh** [comment]
@jmm, I think the OP is a bit misworded. The output is the same regardless of version (correctly `["b"]`). detective has [this optimization](https://github.com/substack/node-detective/blob/aa1700035cabe9c5ec7cdbab5be79f8fdb9e20be/index.js#L41-L42) where is checks the source string for something that _may_ look like a `require`, before even bothering to parse the AST. If the word "require" doesn't show up in the source, then you can be pretty sure that there *isn't* a `require` call. In the case where a word like "require" shows up in comments (like in jQuery), but not in code, you're parsing the AST for nothing. Stripping comments from source is pretty cheap, so it might be worth doing that before doing the fast check.

**Comment by jmm** [comment]
@zertosh Ah, gotcha, thanks for the explanation. I knew about that test, but I didn't connect the dots because I misinterpreted "parses" in the OP. I was also thrown off by the inclusion of the legit `require()` in the example.

> Stripping comments from source is pretty cheap, so it might be worth doing that before doing the fast check.

Do you think it'd make sense to do the fast check, then, if that was positive, strip the comments and try it again?

**Comment by jaydenseric** [comment]
This is a pretty bad bug, and is easily encountered:

```js
// eslint-disable-next-line require-jsdoc
function foo() {}
```

```js
/**
 * Does foo.
 * @example
 * const foo = require('foo')
 * foo()
 */
export default function foo() {}
```

This issue appears to cause https://github.com/documentationjs/documentation/issues/1090.

**Comment by goto-bus-stop** [comment]
The issue there is that detective doesn't support JSX or ES modules syntax. It should not be run on JSX or ES modules files in the first place.

**Comment by jaydenseric** [comment]
@goto-bus-stop no, the point I'm making in this issue here is that people often use JSDoc `@example` comments that contain `require`, and `// eslint-disable-next-line require-jsdoc` comments which also contains `require`.

**Comment by goto-bus-stop** [comment]
This issue is not about a bug but an optimization. Implementing the optimization would only hide the issue you're describing, not fix it. It would pop back up the moment someone uses a string that contains 'require', or uses a method named `someobj.require()`, for example.

**Comment by jaydenseric** [comment]
@goto-bus-stop 

> This issue is not about a bug but an optimization.

This is the repo description:

> Find all calls to require() no matter how deeply nested using a proper walk of the AST

If this causing a false positive is not a bug, then I don't know what is…

```js
// eslint-disable-next-line require-jsdoc
```

There is clearly no call to `require()` in that code. I could tell that with simple regex, let along a “proper walk of the AST”.

I'm happy to be corrected if I'm confused, or misdiagnosed something 😕

**Comment by jaydenseric** [comment]
> The require string occuring inside a comment just means detective will parse the file to do the AST walk to check for require calls. If the word require does not occur in the file at all, detective doesn't even parse it and just returns an empty array immediately.

Bingo! That makes sense to me now, thanks :)

I was thinking it was reporting the actual strings.
