### ISSUE TITLE
Add support for ES6 template functions

### ISSUE THREAD

**Issue by vorg** [browserify/detective#62]
I've tried to use `installify` (it's based on detective) with `hyperx` and it fails at the template string function from this example https://github.com/substack/hyperx:

``` javascript
var vdom = require('virtual-dom')
var hyperx = require('hyperx')
var hx = hyperx(vdom.h)
...
return hx`<div>
    <h1>clicked ${state.times} times</h1>
    <button onclick=${onclick}>click me!</button>
  </div>`
```

**Comment by goto-bus-stop** [comment]
this is fixed in recentish v4 versions. thanks!
