### ISSUE TITLE
Newer keywords like async/await is not supported

### ISSUE THREAD

**Issue by martinwebrant** [browserify/detective#66]
Would be great if you upgraded the acorn package to a newer version that understands async/await so that one can bundle such code in browserify.
I would like to skip transpiling such code to get better debugger experience.

**Comment by martinwebrant** [comment]
ecmaVersion needs to default to 7 in the parse function and acorn must support the keyword as well...

**Comment by brandonhorst** [comment]
More thoughts on this? Async/await is enabled Acorn if `ecmaVersion` is set to 8. Node v7 supports it with the `--harmony-async-await` flag, and Chrome supports it in stable. I don't see why Browserify should be tripping over `async` at this point. Are you open to PRs?

**Comment by Joris-van-der-Wel** [comment]
> ecmaVersion needs to default to 7 in the parse function and acorn must support the keyword as well...

`async`/`await` is supported in acorn v4 if `{ecmaVersion: 8}` is passed.

**Comment by goto-bus-stop** [comment]
fixed in 9d0eb013ac3bb262b36dbbb53560cdca948b2fa5. thanks!
